name: code deployment
on: 
 push: 
  branches:
     -main
    
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      -name: checkout
      uses: action/checkout@v1      

      -name: configure-aws-credentials@v1
       uses: aws-action/configure-aws-credentials@v1
       with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-est-1

        -name: deploy static site to s3 bucket
         run: aws s3 sync . s3://nobita32 --delete
